apiVersion: v1
kind: PersistentVolume
metadata:
  name: r2-static-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - hard
    - noatime
  nfs:
    server: 192.168.0.2
    path: /volume1/r2archive-static
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: r2-static
  namespace: r2
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeName: r2-static-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: r2-data-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
    - hard
    - noatime
  nfs:
    server: 192.168.0.2
    path: /volume1/r2archive-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: r2-data
  namespace: r2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: ""
  volumeName: r2-data-pv
